baseURL = "/"
defaultContentLanguage = "cn"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
paginate = "12"
show_email_in_nav = "false"
summaryLength = "10"
theme = "editor"
title = "星辰通讯社"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "其他文章"
parent = "更多"
url = "others/"
weight = 3
[[menu.main]]
name = "所有文章"
parent = "更多"
url = "news/"
weight = 1
[[menu.main]]
name = "新闻归档"
parent = "更多"
url = "archived-news/"
weight = 2
[[menu.main]]
hasChildren = true
name = "更多"
weight = 3
[[menu.main]]
name = "关于"
url = "about/"
weight = 2
[[menu.main]]
name = "首页"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = ""
author = "星辰通讯社"
contact_form_action = "#"
custom_script = ""
description = "俯瞰昆仑，仰望星辰"
email = ""
favicon = "images/favicon/favicon.ico"
logo = "images/InterImm_logo.png"
logo_height = "26px"
logo_rotate = true
logo_text = "新闻"
mainSections = ["news"]
mobile = ""
search = true
[params.cookies]
enable = false
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = false
preloader = ""
[params.subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[params.variables]
black = "#000000"
dark = "#2B2C2E"
gray = "#66676d"
h1 = "68px"
h1_lg = "52px"
h1_md = "40px"
h2 = "42px"
h2_md = "36px"
h3 = "32px"
h3_md = "28px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
icon_font = "Font Awesome 5 Free"
light = "#a8aab2"
primary_color = "#c98664"
primary_font = "Lora:wght@500;600"
secondary_color = "#c98665"
secondary_font = "Work Sans:wght@400;500;600"
white = "#ffffff"
[params.widgets]
sidebar = ["about-me", "recent-post", "categories", "tags"]
[[params.social]]
icon = "fab fa-github"
link = "https://github.com/IvyChere/ivychere.github.io/"
title = "Github"
